  export const RUBRIC_BLOCK = `
Use the following holistic rubric to score from 0 to 10 based on overall quality:
0 INVALID        | FABRICATED, IRRELEVANT, NONSENSICAL, NO_UNDERSTANDING
1 BROKEN         | CONFUSED, INCOHERENT, OFF_TOPIC, NO_LOGIC
2 WEAK           | MINIMAL_CONTENT, SHALLOW, MISALIGNED, MAJOR_ERRORS
3 FRAGMENTED     | WEAK_EXPLANATION, FLAWED_IDEAS, GAPS
4 LIMITED        | BASIC_IDEAS, SOME_RELEVANCE, MINOR_ERRORS
5 PARTIAL        | MIXED_ACCURACY, SIMPLE_STRUCTURE, LACKS_CLARITY
6 ADEQUATE       | MOSTLY_CORRECT, FAIRLY_CLEAR, MINOR_GAPS
7 COMPETENT      | SOLID_UNDERSTANDING, ORGANIZED, SLIGHT_OMISSIONS
8 STRONG         | CLEAR, COHERENT, WELL_REASONED, MINOR_WEAKNESS
9 NEAR_PERFECT   | HIGHLY_ACCURATE, WELL_EXPRESSED, TINY_OMISSION
10 EXEMPLARY     | MASTERED, STRUCTURED, INSIGHTFUL
`;